[[main]]
name = "Palestras"
url = "#schedule"
weight = 1

[[main]]
name = "Conversas"
url = "#speakers"
weight = 2

[[main]]
name = "Patrocinadores"
url = "#sponsors"
weight = 3

[[main]]
name = "Blog"
url = "#blog"
weight = 4

[[main]]
name = "CÃ³digo de conduta"
url = "/codigo-de-conduta/"
weight = 5
