[[main]]
name = "Programa"
url = "#schedule"
weight = 1

[[main]]
name = "Blog"
url = "#blog"
weight = 2

[[main]]
name = "Patrocinadores"
url = "#sponsors"
weight = 3

[[main]]
name = "Colaboradores"
url = "#supporters"
weight = 4

[[main]]
name = "Ubicación"
url = "#local"
weight = 5

[[main]]
name = "Alojamiento"
url = "#accommodation"
weight = 6

[[main]]
name = "Código de conducta"
url = "/codigo-de-conduta/"
weight = 7
