[[main]]
name = "Talks"
url = "#schedule"
weight = 1

[[main]]
name = "Conversations"
url = "#speakers"
weight = 2

[[main]]
name = "Sponsors"
url = "#sponsors"
weight = 3

[[main]]
name = "Blog"
url = "#blog"
weight = 4

[[main]]
name = "Code of Conduct"
url = "/code-of-conduct/"
weight = 5
