[[main]]
name = "Programação"
url = "#schedule"
weight = 1

[[main]]
name = "Blog"
url = "#blog"
weight = 2

[[main]]
name = "Patrocinadores"
url = "#sponsors"
weight = 3

[[main]]
name = "Apoiadores"
url = "#supporters"
weight = 4

[[main]]
name = "Local"
url = "#local"
weight = 5

[[main]]
name = "Hospedagem"
url = "#accommodation"
weight = 6

[[main]]
name = "Código de conduta"
url = "/codigo-de-conduta/"
weight = 7
