[[main]]
name = "Schedule"
url = "#schedule"
weight = 1

[[main]]
name = "Blog"
url = "#blog"
weight = 2

[[main]]
name = "Sponsors"
url = "#sponsors"
weight = 3

[[main]]
name = "Supporters"
url = "#supporters"
weight = 4

[[main]]
name = "Venue"
url = "#local"
weight = 5

[[main]]
name = "Accommodation"
url = "#accommodation"
weight = 6

[[main]]
name = "Code of Conduct"
url = "/codigo-de-conduta/"
weight = 7
